# Generated by Django 3.1.4 on 2020-12-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='住址')),
                ('TEDT0A', models.DateTimeField(verbose_name='生效时间')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='出险时间')),
                ('reason', models.TextField(verbose_name='事故原因')),
                ('apply_type', models.CharField(max_length=50, verbose_name='申请类别')),
                ('maimlist', models.CharField(max_length=18, verbose_name='伤残等级')),
                ('money', models.FloatField(verbose_name='发票金额')),
                ('compensate', models.FloatField(verbose_name='第三方赔付')),
                ('to_letter', models.CharField(max_length=18, verbose_name='交件人')),
                ('from_letter', models.CharField(max_length=255, verbose_name='收件人')),
                ('receipt_time', models.DateTimeField(verbose_name='收件时间')),
                ('bank', models.CharField(max_length=255, verbose_name='银行')),
                ('bank_account', models.CharField(max_length=32, verbose_name='银行账号')),
                ('reparations', models.FloatField(verbose_name='赔款')),
                ('payee', models.CharField(max_length=255, verbose_name='领款人')),
                ('finishedtime', models.DateTimeField(verbose_name='完成日期')),
                ('amount', models.SmallIntegerField(verbose_name='数量')),
                ('transfer_accounts', models.CharField(max_length=255, verbose_name='转账')),
                ('case_status', models.SmallIntegerField(choices=[(1, '完成'), (2, '正在处理'), (3, '未完成')], verbose_name='案件状态')),
                ('organization', models.CharField(max_length=255, verbose_name='机构')),
                ('file_status', models.SmallIntegerField(choices=[(1, '完成'), (2, '正在处理'), (3, '未完成')], verbose_name='资料状态')),
                ('comment1', models.TextField(verbose_name='备注1')),
                ('comment2', models.TextField(verbose_name='备注2')),
                ('case_info', models.CharField(max_length=255, verbose_name='案件处理')),
                ('other_reason', models.CharField(max_length=255, verbose_name='退案拒赔及原因')),
                ('status', models.SmallIntegerField(choices=[(1, '完成'), (2, '正在处理'), (3, '未完成')], verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameA', models.CharField(max_length=18, verbose_name='姓名')),
                ('IdTypeA', models.SmallIntegerField(choices=[(1, '身份证'), (2, '护照')], default=1, verbose_name='证件类型')),
                ('IDCardNumA', models.CharField(max_length=32, verbose_name='证件号码')),
                ('SexA', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('BirthA', models.DateField(verbose_name='出生日期')),
                ('spanAgeA', models.IntegerField(verbose_name='本卡生效时年龄')),
                ('EMailA', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('PhoneA', models.CharField(max_length=11, verbose_name='手机号码')),
                ('AddrA', models.CharField(max_length=120, verbose_name='联系地址')),
                ('RelashipE', models.BooleanField(default=True, verbose_name='是投保人')),
                ('NameE', models.CharField(max_length=18, verbose_name='被保人姓名')),
                ('IdTypeE', models.SmallIntegerField(choices=[(1, '身份证'), (2, '护照')], default=1, verbose_name='被保人证件类型')),
                ('IDCardNumE', models.CharField(max_length=32, verbose_name='被保人证件号码')),
                ('SexE', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='被保人性别')),
                ('BirthE', models.DateField(verbose_name='被保人出生日期')),
                ('spanAgeE', models.IntegerField(verbose_name='被保人本卡生效时年龄')),
                ('EMailE', models.EmailField(max_length=254, verbose_name='被保人电子邮件')),
                ('PhoneE', models.CharField(max_length=11, verbose_name='被保人手机号码')),
                ('AddrE', models.CharField(max_length=120, verbose_name='被保人联系地址')),
                ('TEDT0A', models.DateField(verbose_name='生效日期')),
            ],
        ),
    ]
