# Generated by Django 3.1.4 on 2020-12-31 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='pwd',
            field=models.CharField(default=1, max_length=88, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
