# Generated by Django 3.1.4 on 2020-12-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0002_policyholder_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyholder',
            name='cardNum',
            field=models.CharField(default=519100004407, max_length=18, verbose_name='卡号'),
            preserve_default=False,
        ),
    ]
